name: flutter_application_1
description: A new Flutter project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  image_picker: ^1.0.8
  table_calendar: ^3.1.2
  permission_handler: ^10.2.0 
  get_storage: ^2.1.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.20.0
  shared_preferences: ^2.2.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/