// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIWIE7ZEa1alc9FoLu0RXK4vTHrGPWFkg',
    appId: '1:1003788111587:web:9dad35688f185745a3ffd6',
    messagingSenderId: '1003788111587',
    projectId: 'penginapanwawan',
    authDomain: 'penginapanwawan.firebaseapp.com',
    storageBucket: 'penginapanwawan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8LFRFY9GZwsugmW8XATHLdBQNtj--hoM',
    appId: '1:1003788111587:android:a86d610b9f648e04a3ffd6',
    messagingSenderId: '1003788111587',
    projectId: 'penginapanwawan',
    storageBucket: 'penginapanwawan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2M1hndJL-p53toKqUbdin5lz-QGs7ZoU',
    appId: '1:1003788111587:ios:cd349d88c0372745a3ffd6',
    messagingSenderId: '1003788111587',
    projectId: 'penginapanwawan',
    storageBucket: 'penginapanwawan.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2M1hndJL-p53toKqUbdin5lz-QGs7ZoU',
    appId: '1:1003788111587:ios:cd349d88c0372745a3ffd6',
    messagingSenderId: '1003788111587',
    projectId: 'penginapanwawan',
    storageBucket: 'penginapanwawan.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIWIE7ZEa1alc9FoLu0RXK4vTHrGPWFkg',
    appId: '1:1003788111587:web:3a6f166e40332172a3ffd6',
    messagingSenderId: '1003788111587',
    projectId: 'penginapanwawan',
    authDomain: 'penginapanwawan.firebaseapp.com',
    storageBucket: 'penginapanwawan.firebasestorage.app',
  );
}
